spring:
  config:
    import: optional:file:.env.properties
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: false
    locations: classpath:db/migration
    schemas: public
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

csv:
  processing:
    base-dir: ${user.dir}
    input-dir: module1/src/main/resources/dataInput
    output-dir: module1/src/main/resources/dataOutput

minio:
  url: ${MINIO_BASE_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET_NAME}